### ISSUE TITLE
Is this compatible with SL 5.1?

### ISSUE THREAD

**Issue by splaisan** [PacificBiosciences/smrtlinkr#1]
I have issues with the first vignette command.

```
df = fetchDataSetsByType("references", server = "smrtlink-beta", port = 8081)
```

I replaced "smrtlink-beta", by my URL but it does not accept https:// in front of the server URL and does not return results without https:// and using either port 8081, 9091, or 8243.

NB: the API GET command works with the URL and port 9091

Any advice on how to actualise this package for SL 5.1 would be welcome or else please specify on the github page that it is not working with it.

We need such toolboxes, please help us accessing the data outside of the SL ecosystem.

Thanks

**Comment by mhsieh** [comment]
You might want to read the API documentation of SMRT-Link 5.1 to fulfill the use case you want to achieve. Unfortunately we currently don't have plan on this project and I might need to mark this project readonly this week. However do feel free to contact our tech support for more assistance.

**Comment by splaisan** [comment]
Hi @mhsieh,
I looked for the r module in the first place because I did not succeed to get the sample setup content through the API from the PB API document yet.

I am now making my own r functions based on the recent API and find that it would help a lot to reach to the data from within R which we all use for data processing and plotting anyway.

Thanks

**Comment by mpkocher** [comment]
@splaisan  I apologize, but this is an internal unofficially support repo and we don't plan to do any further development. It's currently out of date with the current 5.1.0 SL web API. 

With regards to accessing the SL web services,  please see the SL docs included with SMRT Link. Specifically (for >= 5.1.0), the swagger rendered documentation can be very useful to understand details of the SMRT Link web API.  The docs are accessible at:

`http://<HOST>:<PORT>/sl/docs/services/ (e.g, `http://smrtlink-release:9090/sl/docs/services/`). 

If possible, it's best to have access to the file system that SL is running on, this enables you to access to output (e.g., alignmentsets, bam, VCF, etc...) from analysis jobs. 

There's a python client that can be a useful example for your R client. http://pbcommand.readthedocs.io/en/latest/services.html

If you need to use auth, please see this gist as an example of how to use the interface with WSO2 to get a token. 

https://gist.github.com/mpkocher/b6e52c971e49528c6fa0ca5559340236

For any further information, please contact PB Tech Support using the standard channels.
